-- Booster Bowl dynamic pick-board metadata
-- Run once in the Supabase SQL Editor.
-- Existing games remain valid; all new columns are nullable so current scoring
-- and existing picks continue to work unchanged.

alter table public.games add column if not exists sport text default 'football';
alter table public.games add column if not exists district text;
alter table public.games add column if not exists home_class text;
alter table public.games add column if not exists home_region text;
alter table public.games add column if not exists away_class text;
alter table public.games add column if not exists away_region text;
alter table public.games add column if not exists is_featured boolean not null default false;
alter table public.games add column if not exists source text;
alter table public.games add column if not exists source_game_id text;
alter table public.games add column if not exists source_url text;
alter table public.games add column if not exists synced_at timestamptz;
alter table public.games add column if not exists sync_status text;
alter table public.games add column if not exists kickoff_at timestamptz;

create index if not exists games_season_week_district_idx on public.games (season, week, district);
create index if not exists games_season_week_featured_idx on public.games (season, week, is_featured);

-- Safe authenticated read function for the current pick-board catalog.
-- Class and region are deliberately combined here for the product UI:
-- stored Class 2 + Region A is returned as Class 2A. Region fields are null so
-- the old standalone Region board is not generated by the client.
create or replace function public.get_pick_board_games(p_season integer, p_week integer)
returns table (
  id bigint,
  away_team text,
  home_team text,
  kickoff_at timestamptz,
  sport text,
  district text,
  away_class text,
  away_region text,
  home_class text,
  home_region text,
  is_featured boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select
    g.id,
    g.away_team,
    g.home_team,
    g.kickoff_at,
    g.sport,
    g.district,
    case
      when g.away_class is null then null
      when g.away_region is null then g.away_class
      else g.away_class || regexp_replace(g.away_region, '^.*([A-D])$', '\1')
    end as away_class,
    null::text as away_region,
    case
      when g.home_class is null then null
      when g.home_region is null then g.home_class
      else g.home_class || regexp_replace(g.home_region, '^.*([A-D])$', '\1')
    end as home_class,
    null::text as home_region,
    g.is_featured
  from public.games g
  where g.season = p_season and g.week = p_week
  order by coalesce(g.kickoff_at, 'infinity'::timestamptz), g.away_team, g.home_team;
$$;

revoke all on function public.get_pick_board_games(integer, integer) from public;
grant execute on function public.get_pick_board_games(integer, integer) to authenticated;
