-- Booster Bowl weekly schedule ingestion pipeline
-- Development migration. Run after vhsl_school_directory.sql.
-- Purpose:
--   1) stage weekly schedule rows from an approved source/export
--   2) normalize and match schools safely
--   3) upsert canonical games without duplicating existing picks/results
--   4) expose rows that require manual review instead of guessing

create table if not exists public.schedule_imports (
  id bigint generated by default as identity primary key,
  source_name text not null,
  source_url text,
  season integer not null,
  week integer not null,
  sport text not null default 'football',
  imported_at timestamptz not null default now(),
  notes text
);

create table if not exists public.schedule_import_rows (
  id bigint generated by default as identity primary key,
  import_id bigint not null references public.schedule_imports(id) on delete cascade,
  source_game_key text,
  away_team_raw text not null,
  home_team_raw text not null,
  kickoff_at timestamptz,
  away_score integer,
  home_score integer,
  is_final boolean not null default false,
  is_featured boolean not null default false,
  status text not null default 'staged'
    check (status in ('staged','matched','imported','review','rejected')),
  away_school_id bigint references public.vhsl_schools(id) on delete set null,
  home_school_id bigint references public.vhsl_schools(id) on delete set null,
  game_id bigint references public.games(id) on delete set null,
  review_note text,
  created_at timestamptz not null default now()
);

create index if not exists schedule_import_rows_import_idx
  on public.schedule_import_rows(import_id);
create index if not exists schedule_import_rows_status_idx
  on public.schedule_import_rows(status);
create unique index if not exists schedule_import_rows_source_key_idx
  on public.schedule_import_rows(import_id, source_game_key)
  where source_game_key is not null;

alter table public.schedule_imports enable row level security;
alter table public.schedule_import_rows enable row level security;

-- No direct authenticated table access. Import/admin SQL owns these staging tables.

-- Match staged rows only when both team names map exactly to one active canonical school.
create or replace function public.match_schedule_import(p_import_id bigint)
returns table (
  row_id bigint,
  status text,
  away_team_raw text,
  home_team_raw text,
  away_school_id bigint,
  home_school_id bigint,
  review_note text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.schedule_import_rows r
  set away_school_id = s.id
  from public.vhsl_schools s
  where r.import_id = p_import_id
    and s.active = true
    and public.normalize_school_name(r.away_team_raw) = s.canonical_name;

  update public.schedule_import_rows r
  set home_school_id = s.id
  from public.vhsl_schools s
  where r.import_id = p_import_id
    and s.active = true
    and public.normalize_school_name(r.home_team_raw) = s.canonical_name;

  update public.schedule_import_rows
  set status = case
        when away_school_id is not null and home_school_id is not null then 'matched'
        else 'review'
      end,
      review_note = case
        when away_school_id is null and home_school_id is null then 'Away and home schools did not match the VHSL directory.'
        when away_school_id is null then 'Away school did not match the VHSL directory.'
        when home_school_id is null then 'Home school did not match the VHSL directory.'
        else null
      end
  where import_id = p_import_id
    and status in ('staged','matched','review');

  return query
  select r.id, r.status, r.away_team_raw, r.home_team_raw,
         r.away_school_id, r.home_school_id, r.review_note
  from public.schedule_import_rows r
  where r.import_id = p_import_id
  order by r.id;
end;
$$;

revoke all on function public.match_schedule_import(bigint) from public;

-- Import matched rows into games.
-- Existing games are found using season/week plus the canonical away/home school IDs.
-- We update schedule metadata only; existing scores/winners are preserved unless
-- the staged row is explicitly final.
create or replace function public.commit_schedule_import(p_import_id bigint)
returns table (
  row_id bigint,
  game_id bigint,
  action text,
  status text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_import public.schedule_imports%rowtype;
  r public.schedule_import_rows%rowtype;
  v_game_id bigint;
  v_action text;
  a public.vhsl_schools%rowtype;
  h public.vhsl_schools%rowtype;
begin
  select * into v_import
  from public.schedule_imports
  where id = p_import_id;

  if not found then
    raise exception 'Schedule import % does not exist', p_import_id;
  end if;

  for r in
    select *
    from public.schedule_import_rows
    where import_id = p_import_id and status = 'matched'
    order by id
  loop
    select * into a from public.vhsl_schools where id = r.away_school_id and active = true;
    select * into h from public.vhsl_schools where id = r.home_school_id and active = true;

    if a.id is null or h.id is null then
      update public.schedule_import_rows
      set status = 'review',
          review_note = 'A matched school became unavailable before import.'
      where id = r.id;
      continue;
    end if;

    select g.id into v_game_id
    from public.games g
    where g.season = v_import.season
      and g.week = v_import.week
      and g.away_school_id = a.id
      and g.home_school_id = h.id
    order by g.id
    limit 1;

    if v_game_id is null then
      insert into public.games (
        season, week, away_team, home_team,
        away_school_id, home_school_id,
        sport, district,
        away_class, away_region,
        home_class, home_region,
        kickoff_at, is_featured,
        source_name, source_url,
        away_score, home_score, is_final
      ) values (
        v_import.season, v_import.week, a.school_name, h.school_name,
        a.id, h.id,
        v_import.sport,
        case when a.district = h.district then a.district else coalesce(h.district, a.district) end,
        a.classification, a.region,
        h.classification, h.region,
        r.kickoff_at, r.is_featured,
        v_import.source_name, v_import.source_url,
        case when r.is_final then r.away_score else null end,
        case when r.is_final then r.home_score else null end,
        r.is_final
      )
      returning id into v_game_id;
      v_action := 'inserted';
    else
      update public.games g
      set away_team = a.school_name,
          home_team = h.school_name,
          sport = v_import.sport,
          district = case when a.district = h.district then a.district else coalesce(h.district, a.district, g.district) end,
          away_class = coalesce(a.classification, g.away_class),
          away_region = coalesce(a.region, g.away_region),
          home_class = coalesce(h.classification, g.home_class),
          home_region = coalesce(h.region, g.home_region),
          kickoff_at = coalesce(r.kickoff_at, g.kickoff_at),
          is_featured = r.is_featured,
          source_name = v_import.source_name,
          source_url = coalesce(v_import.source_url, g.source_url),
          away_score = case when r.is_final then r.away_score else g.away_score end,
          home_score = case when r.is_final then r.home_score else g.home_score end,
          is_final = case when r.is_final then true else g.is_final end
      where g.id = v_game_id;
      v_action := 'updated';
    end if;

    update public.schedule_import_rows
    set status = 'imported', game_id = v_game_id, review_note = null
    where id = r.id;

    row_id := r.id;
    game_id := v_game_id;
    action := v_action;
    status := 'imported';
    return next;
  end loop;
end;
$$;

revoke all on function public.commit_schedule_import(bigint) from public;

-- Review queue for data-quality checks before publishing a week's board.
create or replace view public.schedule_import_review_queue as
select
  i.id as import_id,
  i.source_name,
  i.season,
  i.week,
  i.sport,
  r.id as row_id,
  r.away_team_raw,
  r.home_team_raw,
  r.kickoff_at,
  r.status,
  r.review_note
from public.schedule_imports i
join public.schedule_import_rows r on r.import_id = i.id
where r.status in ('staged','review')
order by i.id desc, r.id;

-- Readiness summary: useful before making a week's board public.
create or replace function public.get_schedule_import_summary(p_import_id bigint)
returns table (
  total_rows bigint,
  staged_rows bigint,
  matched_rows bigint,
  imported_rows bigint,
  review_rows bigint,
  rejected_rows bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    count(*)::bigint,
    count(*) filter (where status = 'staged')::bigint,
    count(*) filter (where status = 'matched')::bigint,
    count(*) filter (where status = 'imported')::bigint,
    count(*) filter (where status = 'review')::bigint,
    count(*) filter (where status = 'rejected')::bigint
  from public.schedule_import_rows
  where import_id = p_import_id;
$$;

revoke all on function public.get_schedule_import_summary(bigint) from public;

comment on table public.schedule_imports is
  'One controlled weekly schedule ingestion batch for Booster Bowl.';
comment on table public.schedule_import_rows is
  'Staged schedule rows that must match canonical VHSL schools before becoming games.';
comment on view public.schedule_import_review_queue is
  'Schedule rows requiring review before they can enter the live games catalog.';
