-- Booster Bowl hidden test-game shared pick board
-- Run once in the Supabase SQL Editor.

create table if not exists public.test_game_picks (
  id bigint generated by default as identity primary key,
  game_id text not null,
  participant_key text not null,
  display_name text not null check (char_length(display_name) between 1 and 40),
  selected_team text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (game_id, participant_key)
);

alter table public.test_game_picks enable row level security;

create index if not exists test_game_picks_game_updated_idx
  on public.test_game_picks (game_id, updated_at desc);

create or replace function public.submit_test_game_pick(
  p_game_id text,
  p_participant_key text,
  p_display_name text,
  p_selected_team text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text := trim(p_display_name);
begin
  if p_game_id <> 'tj-armstrong-second-half-test' then
    raise exception 'Unknown test game';
  end if;

  if p_selected_team not in ('Thomas Jefferson–Richmond', 'Armstrong') then
    raise exception 'Invalid team selection';
  end if;

  if char_length(v_name) < 1 or char_length(v_name) > 40 then
    raise exception 'Display name must be between 1 and 40 characters';
  end if;

  if char_length(coalesce(p_participant_key, '')) < 12
     or char_length(p_participant_key) > 100 then
    raise exception 'Invalid participant key';
  end if;

  insert into public.test_game_picks (
    game_id,
    participant_key,
    display_name,
    selected_team
  )
  values (
    p_game_id,
    p_participant_key,
    v_name,
    p_selected_team
  )
  on conflict (game_id, participant_key)
  do update set
    display_name = excluded.display_name,
    selected_team = excluded.selected_team,
    updated_at = now();
end;
$$;

create or replace function public.get_test_game_picks(p_game_id text)
returns table (
  display_name text,
  selected_team text,
  updated_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select p.display_name, p.selected_team, p.updated_at
  from public.test_game_picks p
  where p.game_id = p_game_id
  order by p.updated_at asc, p.display_name asc;
$$;

revoke all on table public.test_game_picks from anon, authenticated;
revoke all on function public.submit_test_game_pick(text, text, text, text) from public;
revoke all on function public.get_test_game_picks(text) from public;

grant execute on function public.submit_test_game_pick(text, text, text, text) to anon, authenticated;
grant execute on function public.get_test_game_picks(text) to anon, authenticated;
