-- Booster Bowl VHSL school directory foundation
-- Development migration: run in Supabase only after review/testing.
-- Normalizes school metadata so weekly games can inherit district/class/region
-- instead of duplicating that information by hand for every matchup.

create table if not exists public.vhsl_schools (
  id bigint generated by default as identity primary key,
  school_name text not null,
  canonical_name text not null,
  city text,
  district text,
  classification text,
  region text,
  active boolean not null default true,
  source_name text,
  source_url text,
  source_checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vhsl_schools_canonical_name_key unique (canonical_name)
);

create index if not exists vhsl_schools_district_idx
  on public.vhsl_schools (district) where active = true;
create index if not exists vhsl_schools_classification_region_idx
  on public.vhsl_schools (classification, region) where active = true;
create index if not exists vhsl_schools_school_name_idx
  on public.vhsl_schools (school_name) where active = true;

alter table public.vhsl_schools enable row level security;

-- Keep the underlying directory protected. The app reads through this RPC.
create or replace function public.get_vhsl_school_directory()
returns table (
  id bigint,
  school_name text,
  city text,
  district text,
  classification text,
  region text
)
language sql
stable
security definer
set search_path = public
as $$
  select s.id, s.school_name, s.city, s.district, s.classification, s.region
  from public.vhsl_schools s
  where s.active = true
  order by s.school_name;
$$;

revoke all on function public.get_vhsl_school_directory() from public;
grant execute on function public.get_vhsl_school_directory() to authenticated;

-- Optional helper for ingestion jobs/admin SQL. It normalizes whitespace/case for
-- matching without changing the human-readable school_name.
create or replace function public.normalize_school_name(p_name text)
returns text
language sql
immutable
strict
as $$
  select lower(regexp_replace(trim(p_name), '\s+', ' ', 'g'));
$$;

comment on table public.vhsl_schools is
  'Canonical VHSL school metadata used to build Booster Bowl district, region, classification and school pick boards.';
comment on column public.vhsl_schools.canonical_name is
  'Normalized matching key, normally produced with public.normalize_school_name(school_name).';
